[package]
name = "rust-shell"
version = "0.1.0"
authors = ["Piush Bose <dev.bosepiush@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
chrono = "0.4.40"
colored = "2.0"
prettytable-rs = "0.10"
